events {} # Pourquoi ???

http{
    server{
        listen 80;
        return 301 https://$host$request_uri;
    }

    server{
        listen              443 ssl;
        ssl_certificate     /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;

        location / {
            proxy_pass http://serveur:8000;
        }
    }
}